[project]
name = "bits_fde"
version = "0.0.1"
authors = [
  {name = "Enki Saura", email = "esaura@ikosconsulting.com"},
]
maintainers = [
  {name = "Enki Saura", email = "esaura@ikosconsulting.com"}
]
description = "Baguette in the sky module for Fault Detection and Exclusion "
dependencies = [
    "baguette_in_the_sky>=0.2.0", # Available at https://github.com/enkisaura/Baguette-In-The-Sky.git
    "pandas",
    "numpy",
    "tqdm",
    "scipy",
    "joblib",
]
requires-python = ">= 3.10"


[tool.pytest.ini_options]
testpaths = ["bits_fde/test"] # Test directory
python_files = ["test_*.py"] # Test files
python_classes = ["Test*"] # Test class
python_functions = ["test_*"] # Test functions
norecursedirs = [".*", "build", "dist", "venv", "env", "__pycache__"] # Not included directories
